### ISSUE TITLE
About reproducing anytime experiment in paper

### ISSUE THREAD

**Issue by luzai** [kalviny/MSDNet-PyTorch#10]
Hi, thank you very much for this repo! May I ask the performance of `step=7/msdnet-step=7-block=5.pth.tar` model on Imagenet anytime prediction task? 

The result I got is 
```
 * prec@1 62.896 prec@5 84.706
 * prec@1 70.316 prec@5 89.590
 * prec@1 73.000 prec@5 91.230
 * prec@1 73.594 prec@5 91.452
 * prec@1 74.592 prec@5 92.066

---------------------
FLOPs: 615.69M, Params: 8.76M
---------------------
FLOPs: 1436.39M, Params: 20.15M
---------------------
FLOPs: 2283.21M, Params: 31.73M
---------------------
FLOPs: 2967.42M, Params: 41.86M
---------------------
FLOPs: 3253.79M, Params: 62.31M
```

It is slightly lower than the performance provided in the figure of paper 
![image](https://user-images.githubusercontent.com/14788650/68593062-8c7d8880-04cf-11ea-93aa-b75525c41b5f.png)

**Comment by kalviny** [comment]
The released model is trained for budgeted prediction. If you want to reproduce the anytime prediction results, you need to train the model with full training set.

**Comment by luzai** [comment]
Thank you very much! I find the detail in paper, "We hold out 50,000 images from the training set to estimate the confidence threshold for classifiers in MSDNet. ", the training setting for budgeted prediction and anytime prediction is different. I will try to train the model with full training set.

**Comment by gdamaskinos** [comment]
Hi @luzai ,

which command did you use to get these numbers?
I execute the command [mentioned in the README.md](https://github.com/kalviny/MSDNet-PyTorch#pre-trained-msdnet-models-on-imagenet) but I get:
`While copying the parameter named "module.classifier.4.linear.weight", whose dimensions in the model are torch.Size([1000, 560]) and whose dimensions in the checkpoint are torch.Size([1000, 976]).`
