### ISSUE TITLE
Pre_trained model

### ISSUE THREAD

**Issue by trinhvg** [kalviny/MSDNet-PyTorch#17]
Your model folder have 2 file index.pth and msdnet-step=4-block=5.pth.tar. Which one I should load to "checkpoint = load_checkpoint(args)"?
I open index.pth, it may not the pretrained weight, while I can't extract msdnet-step=4-block=5.pth.tar.
Thank you

**Comment by cpsxhao** [comment]
msdnet-step=4-block=5.pth.tar is the model checkpoint. Don't extract it, just load it using pytorch.

index.pth is the file used for split the devset apart from trainset (If I remember correctly).

**Comment by trinhvg** [comment]
It worked. Thank u for quick support.
