### ISSUE TITLE
How to save the flops.pth of MSDNet in adaptive_inference.py?

### ISSUE THREAD

**Issue by favorxin** [kalviny/MSDNet-PyTorch#3]
Hi author, thanks for your work, but I do not understand the dynamic evaluation in origin paper and how does it works in the code. I can not fine the way to compute and save the flops in your code. Can you send me the code about this point? cause I think I can understand paper by code. Thank you very much.

**Comment by kalviny** [comment]
I have updated the `op_counter.py` to get the flops. However, if you want to do the _lazy evaluation_, you should manually prune the extra budget.
