### ISSUE TITLE
Configure of step7

### ISSUE THREAD

**Issue by mileyan** [kalviny/MSDNet-PyTorch#7]
Hi, thanks for your work. This code is pretty clean and nice. I want to do get the result of imagenet step7. Can you add the inference command for step 7 imagenet?

**Comment by kalviny** [comment]
Hi, following script is the inference configuration for step = 7. 

`python3 main.py --data-root /PATH/TO/ImageNet --data ImageNet --save /PATH/TO/SAVE \
                --arch msdnet --batch-size 256 --epochs 90 --nBlocks 5 \
                --stepmode even --step 7 --base 7 --nChannels 32 --growthRate 16 \
                --grFactor 1-2-4-4 --bnFactor 1-2-4-4 \
                --evalmode dynamic --evaluate-from /PATH/TO/CHECKPOINT/ \
                --use-valid --gpu 0,1,2,3 -j 16 \
`
